### ISSUE TITLE
Unable to grab transactions

### ISSUE THREAD

**Issue by mdholbrook** [mmrobins/creditkarma_export_transactions#1]
I'm happy to have found your project, as I learned that the final transaction export from Mint failed (results were heavily filtered). I am having issues grabbing my transactions (see below). Is this a known issue, or did something change on the site which breaks your tool?

```
D:\Documents\BudgetComparison\creditkarma_export_transactions>ruby fetch_credit_karma_transactions
fetch_credit_karma_transactions:3932:in `<main>': undefined method `[]' for nil (NoMethodError)

  tra_batch = resp['data']['prime']['transactionsHub']['transactionPage']['transactions'].map do |tra|
```

I am running on Windows 10, ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [i386-mingw32]

**Comment by stereotypy** [comment]
Hi, I also have a similar issue:
`fetch_credit_karma_transactions:3945:in `block in <main>': undefined method `[]' for nil (NoMethodError)

    merch = tra['merchant']['name']
`
would really appreciate if you could take a look @mmrobins :)

**Comment by mykamiller** [comment]
Hi, I'm having this issue as well

```
fetch_credit_karma_transactions.rb:3945:in `block in <main>': undefined method `[]' for nil (NoMethodError)

    merch = tra['merchant']['name']
                           ^^^^^^^^
        from fetch_credit_karma_transactions.rb:3932:in `map'
        from fetch_credit_karma_transactions.rb:3932:in `<main>'
```

**Comment by mmrobins** [comment]
Updated to address.  2 separate issues here really, but I hit both on re-running the script

1. 2FA not triggered by https://www.creditkarma.com/today, instead response was just empty.  This was the original issues report
2. Sometimes merchant is now empty.  Not sure why that's new

Either way, both should be addressed, and hopefully I'm handling hash access better for future error reporting too

**Comment by stereotypy** [comment]
Thank you!! Seems to be working fine now
